export const tasks = [
    {
        id: 1,
        title: 'ABC of Code Review',
        duedate: 'August 3, 2021',
        type: 'Course',
        status: 'Completed',
        user: 1
    },
    {
        id: 2,
        title: 'Oratory and Presentations',
        duedate: 'August 25, 2021',
        type: 'Course',
        status: 'Active',
        user: 2
    },
    {
        id: 3,
        title: 'How to build a Full Stack App',
        duedate: 'October 15, 2021',
        type: 'Course',
        status: 'Active',
        user: 3
    },
    {
        id: 4,
        title: 'Fintech Values',
        duedate: 'August 10, 2021',
        type: 'Course',
        status: 'Completed',
        user: 4
    },
    {
        id: 5,
        title: 'Scrum - from zero to hero',
        duedate: 'July 27, 2021',
        type: 'Course',
        status: 'Ended',
        user: 5
    },
]

export const users = [
    {
        id: 1,
        name: 'Andrea Lamas',
        email: 'andrealamas@mail.com',
        img: 'https://randomuser.me/api/portraits/women/90.jpg',
        company: 'Asana',
        role: 'UX/UI Lead',
        forecast: '30%',
        activity: '6 Hours ago',
    },
    {
        id: 2,
        name: 'Rodrigo Ferrari',
        email: 'rodrigoferrari@mail.com',
        img: 'https://randomuser.me/api/portraits/men/36.jpg',
        company: 'Google',
        role: 'Tech Lead',
        forecast: '10%',
        activity: '15 Hours ago',
    },
    {
        id: 3,
        name: 'Jorge Carranza',
        email: 'jorgecarranza@mail.com',
        img: 'https://randomuser.me/api/portraits/men/11.jpg',
        company: 'Auth0',
        role: 'Senior Dev',
        forecast: '41%',
        activity: 'Aug 10, 2021',
    },
    {
        id: 4,
        name: 'Daniela Praga',
        email: 'danielapraga@mail.com',
        img: 'https://randomuser.me/api/portraits/women/28.jpg',
        company: 'Coca Cola',
        role: 'QA',
        forecast: '63%',
        activity: '2 Hours ago',
    },
    {
        id: 5,
        name: 'Julio Trotta',
        email: 'juliotrotta@mail.com',
        img: 'https://randomuser.me/api/portraits/men/46.jpg',
        company: 'Mercado Libre',
        role: 'Back End Lead',
        forecast: '30%',
        activity: '6 Hours ago',
    },
    {
        id: 6,
        name: 'Rosana Lorenzato',
        email: 'rosanalorenzato@mail.com',
        img: 'https://randomuser.me/api/portraits/women/65.jpg',
        company: 'Mercado Libre',
        role: 'Front End Lead',
        forecast: '40%',
        activity: 'August 2, 2021',
    },
    {
        id: 7,
        name: 'Ricardo Malfran',
        email: 'ricardomalfran@mail.com',
        img: 'https://randomuser.me/api/portraits/men/24.jpg',
        company: 'Media Monks',
        role: 'Dev Op',
        forecast: '71%',
        activity: '1 Hour ago',
    },
    {
        id: 8,
        name: 'Belén Aguirre',
        email: 'belenaguirre@mail.com',
        img: 'https://randomuser.me/api/portraits/women/74.jpg',
        company: 'Coder House',
        role: 'Full Stack Dev',
        forecast: '55%',
        activity: '22 Hours ago',
    },
    {
        id: 9,
        name: 'Amilkar Figueroa',
        email: 'amilkarfigueroa@mail.com',
        img: 'https://randomuser.me/api/portraits/men/27.jpg',
        company: 'Plataforma 5',
        role: 'Tech Lead',
        forecast: '15%',
        activity: 'July 3, 2021',
    },
    {
        id: 10,
        name: 'Diego Pereyra',
        email: 'facundopereyra@mail.com',
        img: 'https://randomuser.me/api/portraits/men/42.jpg',
        company: 'Banco Santander',
        role: 'Front End Dev',
        forecast: '85%',
        activity: '3 Hours ago',
    },
]